### ISSUE TITLE
Type error on slide

### ISSUE THREAD

**Issue by elrikdante** [pietervdvn/Haskell#12]
This should be:

lookup :: a -> [(a,b)] -> Maybe b

<img width="860" alt="screen shot 2015-12-28 at 10 52 46 pm" src="https://cloud.githubusercontent.com/assets/358712/12029313/d17da84a-adb5-11e5-86fb-20c7f1e60518.png">

BTW these resources are excellent. Thank you!

Regards,
Dante Elrik

**Comment by pietervdvn** [comment]
Indeed! Thanks for pointing out.

Are you Dutch speaking? Most of the resources have some Dutch in them

**Comment by elrikdante** [comment]
No, but the type system is acting as a good intermediate layer =)

It definitely looks like a cool language, and these programs tend to use more commands than nouns (so that helps with grokking.)

but long story short:  until these slides, I'd never looked at dutch text. LMK if you're down to tutor me dutch/haskell =) .

Thanks again for these slides (and included exercises.)

Regards,
Dante Elrik

**Comment by pietervdvn** [comment]
Down the rabbit hole XD

Feel free to send the excercises you make, I'll have a look at them. Translating everything is a little to much, as I'm having to study for exams.

Perhaps you can checkout http://learnyouahaskell.com/ , which is free and in English

**Comment by elrikdante** [comment]
Haha =) No worries! 

[I'm joking about the haskell] <- (redacted) -- nope, but serious about the dutch =] 

also whats your twitter? if you don't mind me asking of course.
regards,
Dante Elrik

**Comment by pietervdvn** [comment]
I'm afraid I don't have the time to either teach you Dutch or Haskell.

And I don't have a twitter. I don't like keeping to much social networks.
