### ISSUE TITLE
Convert to English

### ISSUE THREAD

**Issue by willisjtc** [pietervdvn/Haskell#13]
This project is written in german, although a fantastic language, it is not universally known.

Dieses Projekt wird in Deutsch geschrieben, obwohl eine fantastische Sprache, ist es nicht allgemein bekannt.

**Comment by pietervdvn** [comment]
It's Dutch (which is spoken in Flemish Belgium and the Netherlands)

The slides were made for a course fur Dutch people, so that's why.

I don't really have the time to translate it... What would you use it for?
